name: Build and run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  strategy:
    matrix:
      os: [ ubuntu-latest, windows-latest, macos-latest ]

  runs-on: ${{ matrix.os }}
  timeout-minutes: 30

  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: "assemble"

    - name: Check
      uses: gradle/gradle-build-action@v2
      with:
        arguments: "check"
