name: Run code quality on commits

on: [push, pull_request]

jobs:
  timeout-minutes: 30

  detekt:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Run Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "detekt"

  klint:
    name: Klint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Run Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "lintKotlin"
