name: Run code quality on commits
on: push
jobs:
  build:
    name: Compile classes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Run Gradle
        run: ./gradlew compileKotlin
  detekt:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Run Gradle
        run: ./gradlew detekt
  klint:
    name: Klint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Run Gradle
        run: ./gradlew lintKotlin