name: Publish artifacts in Space
on:
  release:
    types: [ published ]
  push:
    branches: [ main ]

jobs:
  publish:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    name: Publish
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Run Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "publish"
        env:
          MAVEN_SPACE_USERNAME: ${{secrets.MAVEN_SPACE_USERNAME}}
          MAVEN_SPACE_PASSWORD: ${{secrets.MAVEN_SPACE_PASSWORD}}
