name: Publish artifacts in Space
on:
  release:
    types: [ published ]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Run Gradle
        run: ./gradlew publish
        env:
          MAVEN_SPACE_URL: ${{secrets.MAVEN_SPACE_URL}}
          MAVEN_SPACE_USERNAME: ${{secrets.MAVEN_SPACE_USERNAME}}
          MAVEN_SPACE_PASSWORD: ${{secrets.MAVEN_SPACE_PASSWORD}}