name: Test with Cache

on:
  push:
    branches:
      [main, fabrizio.scarponi/cache-integration]
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
#      - name: Build with Gradle
#        env:
#          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
#        run: ./gradlew build --no-daemon
      - name: Run tests for cache system
        run: ./gradlew :http:client:jvmTest --tests "CacheTests"